# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).

collectionCar = WordCollection.create(name: 'Car/Samochód', public: true)
Word.create(definition:'antifreeze', translation: 'płyn chłodniczy', word_collection_id: collectionCar.id)
Word.create(definition:'battery', translation: 'akumulator', word_collection_id: collectionCar.id)
Word.create(definition:'brake disc', translation: 'tarcze hamulcowe', word_collection_id: collectionCar.id)
Word.create(definition:'brake fluid', translation: 'płyn hamulcowy', word_collection_id: collectionCar.id)
Word.create(definition:'brake pedal', translation: 'pedał hamulca', word_collection_id: collectionCar.id)
Word.create(definition:'braking pads', translation: 'klocki hamulcowe', word_collection_id: collectionCar.id)
Word.create(definition:'camshaft', translation: 'rozrząd', word_collection_id: collectionCar.id)
Word.create(definition:'clutch', translation: 'sprzęgło', word_collection_id: collectionCar.id)
Word.create(definition:'engine', translation: 'silnik', word_collection_id: collectionCar.id)
Word.create(definition:'engine oil', translation: 'olej silnikowy', word_collection_id: collectionCar.id)
Word.create(definition:'gas pedal', translation: 'pedał gazu', word_collection_id: collectionCar.id)
Word.create(definition:'gearbox', translation: 'skrzynia biegów', word_collection_id: collectionCar.id)
Word.create(definition:'handbrake', translation: 'hamulec ręczny', word_collection_id: collectionCar.id)
Word.create(definition:'oil pan', translation: 'miska olejowa', word_collection_id: collectionCar.id)
Word.create(definition:'radiator', translation: 'chłodnica', word_collection_id: collectionCar.id)
Word.create(definition:'rim', translation: 'felga', word_collection_id: collectionCar.id)
Word.create(definition:'screen wash', translation: 'płyn do spryskiwaczy', word_collection_id: collectionCar.id)
Word.create(definition:'shock absorber', translation: 'amortyzatory', word_collection_id: collectionCar.id)
Word.create(definition:'steering wheel', translation: 'kierownica', word_collection_id: collectionCar.id)
Word.create(definition:'tire', translation: 'opona', word_collection_id: collectionCar.id)

collectionHuman = WordCollection.create(name: 'Human/Człowiek', public: true)
Word.create(definition: 'appendix', translation: 'wyrostek robaczkowy', word_collection_id: collectionHuman.id)
Word.create(definition: 'artery', translation: 'tętnica', word_collection_id: collectionHuman.id)
Word.create(definition: 'brain', translation: 'mózg', word_collection_id: collectionHuman.id)
Word.create(definition: 'cerebellum', translation: 'móżdżek', word_collection_id: collectionHuman.id)
Word.create(definition: 'diaphragm', translation: 'przepona', word_collection_id: collectionHuman.id)
Word.create(definition: 'duodenum', translation: 'dwunastnica', word_collection_id: collectionHuman.id)
Word.create(definition: 'heart', translation: 'serce', word_collection_id: collectionHuman.id)
Word.create(definition: 'kidney', translation: 'nerka', word_collection_id: collectionHuman.id)
Word.create(definition: 'large intestine', translation: 'jelito grube', word_collection_id: collectionHuman.id)
Word.create(definition: 'larynx', translation: 'krtań', word_collection_id: collectionHuman.id)
Word.create(definition: 'liver', translation: 'wątroba', word_collection_id: collectionHuman.id)
Word.create(definition: 'lower jaw', translation: 'żuchwa', word_collection_id: collectionHuman.id)
Word.create(definition: 'lung', translation: 'płuco', word_collection_id: collectionHuman.id)
Word.create(definition: 'small intestine', translation: 'jelito cienkie', word_collection_id: collectionHuman.id)
Word.create(definition: 'spinal cord', translation: 'rdzeń kręgowy', word_collection_id: collectionHuman.id)
Word.create(definition: 'spleen', translation: 'śledziona', word_collection_id: collectionHuman.id)
Word.create(definition: 'stomach', translation: 'żołądek', word_collection_id: collectionHuman.id)
Word.create(definition: 'thyroid', translation: 'tarczyca', word_collection_id: collectionHuman.id)
Word.create(definition: 'trachea', translation: 'tchawica', word_collection_id: collectionHuman.id)
Word.create(definition: 'vein', translation: 'żyła', word_collection_id: collectionHuman.id)

collectionComputer = WordCollection.create(name: 'Computer/Komputer', public: true)
Word.create(definition: 'central processing unit (CPU)', translation: 'procesor', word_collection_id: collectionComputer.id)
Word.create(definition: 'computer cooling', translation: 'chłodzenie komputera', word_collection_id: collectionComputer.id)
Word.create(definition: 'driver', translation: 'sterownik', word_collection_id: collectionComputer.id)
Word.create(definition: 'fan', translation: 'wentylator', word_collection_id: collectionComputer.id)
Word.create(definition: 'fibre-optic', translation: 'światłowód', word_collection_id: collectionComputer.id)
Word.create(definition: 'floppy disc', translation: 'dyskietka', word_collection_id: collectionComputer.id)
Word.create(definition: 'floppy drive', translation: 'stacja dysków', word_collection_id: collectionComputer.id)
Word.create(definition: 'graphic card', translation: 'karta graficzna', word_collection_id: collectionComputer.id)
Word.create(definition: 'hard disc', translation: 'dysk twardy', word_collection_id: collectionComputer.id)
Word.create(definition: 'keyboard', translation: 'klawiatura', word_collection_id: collectionComputer.id)
Word.create(definition: 'local area network (LAN)', translation: 'sieć lokalna', word_collection_id: collectionComputer.id)
Word.create(definition: 'monitor', translation: 'monitor', word_collection_id: collectionComputer.id)
Word.create(definition: 'motherboard', translation: 'płyta główna', word_collection_id: collectionComputer.id)
Word.create(definition: 'mouse', translation: 'myszka', word_collection_id: collectionComputer.id)
Word.create(definition: 'network card', translation: 'karta sieciowa', word_collection_id: collectionComputer.id)
Word.create(definition: 'power pack', translation: 'zasilacz', word_collection_id: collectionComputer.id)
Word.create(definition: 'protocol', translation: 'protokół', word_collection_id: collectionComputer.id)
Word.create(definition: 'random access memory (RAM)', translation: 'pamięć losowego dostępu', word_collection_id: collectionComputer.id)
Word.create(definition: 'read only memory (ROM)', translation: 'pamięć stała', word_collection_id: collectionComputer.id)
Word.create(definition: 'sound card', translation: 'karta dźwiękowa', word_collection_id: collectionComputer.id)